name: Run Python Script Daily

on:
  schedule:
    - cron: '20 14 * * *'  # Chạy vào lúc 9:20 tối GMT+7
  workflow_dispatch:        # Thêm trigger này để bật nút "Run workflow"


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Chọn phiên bản Python phù hợp

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas csv requests beautifulsoup4  # Cài đặt các thư viện cần thiết

      - name: Run Python script
        run: python script.py  # Chạy file script.py
