name: Run Python Script Daily

on:
  schedule:
    - cron: '20 14 * * *'  # Chạy vào lúc 9:20 tối GMT+7
  workflow_dispatch:        # Cho phép chạy thủ công

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Nâng cấp Python lên 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4  # Loại bỏ csv vì không cần thiết

      - name: Run Python script
        run: python script.py  # Chạy file script.py
