name: Schedule Crawl.ipynb

on:
  schedule:
    - cron: '30 8-23/1 * * *'  # Run at 8:30 AM UTC, then every 5 minutes after that
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub Actions UI

jobs:
  run-crawl:
    runs-on: ubuntu-latest  # Chạy trên Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Lấy mã nguồn từ repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Cài đặt Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Cài đặt các dependencies trong file requirements.txt
          pip install jupyter  # Cài đặt Jupyter nếu chưa có

      - name: Run Crawl.ipynb
        run: |
          jupyter nbconvert --to notebook --execute Crawl.ipynb --output result.ipynb  # Thực thi Crawl.ipynb
