name: Schedule Crawl.ipynb

on:
  schedule:
    # Cron expression for every 5 minutes starting from 8:30 AM UTC
    - cron: '0 0-23/1 * * *'  # Run at 8:30 AM UTC, then every 5 minutes after that
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  run-crawl:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Install Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the required dependencies in requirements.txt
          pip install jupyter  # Install Jupyter if not already installed

      - name: Run Crawl.ipynb
        run: |
          jupyter nbconvert --to notebook --execute Crawl.ipynb --output result.ipynb  # Execute Crawl.ipynb
